name: My First App
on: pull_request

jobs:
  my-first-job:
    runs-on: ubuntu-latest

    steps:
      - name: List Files
        run: ls
      - name: Create JS File
        run: echo "Fahad Bhati" > text.js
      - name: List Files
        run: ls
      - name: Create Node File
        run: echo "console.log("Fahad Bhati")" > demo.mjs
      - name: List Files
        run: ls
